jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: 'https://server.seocifybd.xyz'
          repository_root: '/home/seocifybd/public_html '
          branch: main
          cpanel_token: 'Z9B4VF58J2YQPOCZAYDPYBDIEHR1WB1K'
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"